require 'yaml'

VAGRANT_API_VERSION = '2'

MACHINES = YAML.load_file('machines.yml')['machines']
  .select do |machine|
    group = machine['group']
    group === 'servers' || group === 'clients'
  end

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  MACHINES.each do |machine|
    name, ip = machine.values_at('name', 'ip')

    config.vm.define name do |machine_config|
      machine_config.vm.box = 'ubuntu/trusty64'
      machine_config.vm.hostname = name
      machine_config.vm.network :private_network, ip: ip
      if machine == MACHINES.last
        machine_config.vm.provision :ansible do |ansible|
          ansible.limit = 'all'
          ansible.playbook = 'playbook.yml'
        end
      end
    end
  end
end
